Repository Emyjakarta/monty, pull requests merged in 2023-12, with the labels that each got.

#1 Added functions for stack operations
  monty.c
  monty.h
  more_utils.c
  stack_ops.c
  utils.c
Labels: enhancement

#2 Removed unused variable
  utils.c
Labels: bug

#3 Added a function to handle the swap opcode
  monty.h
  stack_ops.c
  utils.c
Labels: enhancement

#4 Created a new function (add)
  .gitignore
  arithmetic_operations.c
  monty.h
  utils.c
Labels: enhancement

#6 Added functions to handle character and string opcodes
  monty.h
  string_opcodes.c
  utils.c
Labels: enhancement

#7 Fixed valgrind uninitialized values error
  utils.c
Labels: bug, enhancement

#8 Improved memory handling for buffer
  memory_handlers.c
  monty.h
  more_utils.c
  utils.c
Labels: bug, enhancement

#9 Updated to handle 'stack' and 'queue' opcodes
  monty.h
  stack_ops.c
  utils.c
Labels: enhancement

#10 Added a function to handle the "rotl" opcode
  monty.h
  rot_opcodes.c
  utils.c
Labels: enhancement

#11 Improved error checking buffer handling
  more_utils.c
  utils.c
Labels: bug, enhancement

#12 Created a new function (rotr)
  rot_opcodes.c
Labels: enhancement

#13 Added a brainf*ck script that adds two numbers
  bf/1001-add.bf
Labels: enhancement

#14 Fixed valgrind uninitialized values error
  memory_handlers.c
Labels: enhancement, valgrind_error

#16 Fixed comment handling so it handles all cases
  utils.c
Labels: bug, enhancement

#17 fixed bug resulting from tabs
  utils.c
Labels: bug

#18 valgrind error/changed malloc to calloc
  stack_ops.c
Labels: valgrind_error

#19 valgrind error/fixed segmentation fault
  utils.c
Labels: valgrind_error

#21 Bugfix/string opcodes
  string_opcodes.c
Labels: bug

#22 Updated to use the 'getline' function & Code Refactored
  monty.h
  more_utils.c
  utils.c
Labels: bug, enhancement

#24 Added a Makefile and bash script for installation
  Makefile
  install.sh
  monty.1
  monty.h
Labels: documentation

#25 Removed residual files after installation and installed the man page
  Makefile
  install.sh
  monty.1
Labels: documentation

#26 Updates/man page and installation
  monty.1
Labels: documentation

#27 Updates/man page and installation
  Makefile
  install.sh
Labels: documentation

#28 Documentation
  utils.c
Labels: documentation
